
site:
  author: nnda
  title: nnda's
  description: My personal website.

repoURL: github.com/nndda/website

nav:
  links:
    - name: Projects
      url: \#projects

    - name: Artworks
      url: \#artworks

    - icon: itchdotio
      url: nnda.itch.io
      external: true

    - icon: artstation
      url: www.artstation.com/nnda
      external: true

    - icon: github
      url: github.com/nndda
      external: true

socials:
  - name: GitHub
    url: github.com/nndda
    icon: github

  - name: itch.io
    url: nnda.itch.io
    icon: itchdotio

  - name: ArtStation
    url: www.artstation.com/nnda
    icon: artstation

  - name: Mastodon
    url: mastodon.art/@nnda
    icon: mastodon

  - name: CodePen
    url: codepen.io/nnda
    icon: codepen

  - name: Patreon
    url: www.patreon.com/nnda
    icon: patreon

  - name: Ko-fi
    url: ko-fi.com/nnda
    icon: kofi

projects:
  - name: Theatre
    url: https://github.com/nndda/Theatre
    labels: [ Godot, GDScript ]
    description: |
      🎭 Yet another (linear) dialogue system/addon/plugin for Godot. Written in human-readable plain text. Compatible with Godot 4.3.

    image: ../assets/project-theatre.webp
    min-height: 280px

  - name: Pitch
    url: https://github.com/nndda/Pitch
    labels: [ Web, TypeScript, SCSS ]
    description: |
      🧩 Collection of UI components and tweaks, designed specifically for itch.io project pages.

    image: ../assets/project-pitch.webp
    min-height: 280px

  - offsetElem: true

  - name: This website
    url: https://github.com/nndda/website
    labels: [ Web, TypeScript, SCSS, Handlebars ]
    description: |
      My personal website, written in TypeScript, SCSS, and Handlebars, bundled with webpack.

repoWorkflowBadges:
  - codeql.yml
  - lint-styles.yml
  - lint-scripts.yml