
site:
  author: nnda
  title: nnda's
  description: My personal website.

repoURL: github.com/nndda/website

nav:
  links:
    - name: Projects
      url: \#projects

    - name: Illustrations
      url: \#illustrations

    - icon: itchdotio
      url: nnda.itch.io
      external: true

    - icon: artstation
      url: www.artstation.com/nnda
      external: true

    - icon: github
      url: github.com/nndda
      external: true

# ------------------------------------------------------------------------------------------------------------------------------------

socials:
  - group: My Main Works
    links:
      - name: GitHub
        url: github.com/nndda
        icon: github
        redirect: /github

      - name: itch.io
        url: nnda.itch.io
        icon: itchdotio
        redirect: /itchio

      - name: Patreon
        url: patreon.com/nnda
        icon: patreon
        redirect: /patreon

  - group: Artworks & Illustrations
    links:
      - name: ArtStation
        url: artstation.com/nnda
        icon: artstation
        redirect: /artstation

      - name: cara.app
        url: cara.app/nnda
        redirect: /cara

# ------------------------------------------------------------------------------------------------------------------------------------

projects:
  - name: Theatre
    url: https://github.com/nndda/Theatre
    labels: [ Godot, GDScript ]
    description: |
      🎭 Yet another (linear) dialogue system/addon/plugin for Godot. Written in human-readable plain text. Compatible with Godot 4.3.

    image: ../assets/project-theatre.webp

  - name: Pitch
    url: https://nnda.itch.io/pitch
    labels: [ Web, TypeScript, SCSS ]
    description: |
      🧩 Collection of UI components and tweaks, designed specifically for itch.io project pages.

    image: ../assets/project-pitch.webp

  - name: This website
    url: https://github.com/nndda/website
    labels: [ Web, TypeScript, SCSS, Handlebars ]
    description: |
      My personal website, written in TypeScript, SCSS, and Handlebars, bundled with webpack.

  - name: itchio-profile
    url: https://github.com/nndda/itchio-profile
    labels: [ Node, JavaScript, SCSS ]
    description: |
      Source code for my itch.io profile page.